authentication/urls.py
from django.urls import path
from authentication import views as l_views

app_name = 'log'

urlpatterns = [
    path('', l_views.login, name='login_login'),
    path('logout/', l_views.logout, name='login_logout'),
    path('register/', l_views.register, name='login_register'),
    path('dashboard/', l_views.dashboard, name='login_dashboard'),

]

menu/urls.py
from django.urls import path
from menu.views import cat_create, cat_list, cat_update, cat_delete

app_name = 'menu'

urlpatterns = [
    path('cats/', cat_list, name="cat_list"),
    path('cats/cat_create', cat_create, name="cat_create"),
    path('cats/cat_update/<int:pk>/', cat_update, name="cat_update"),
    path('cats/cat_delete/<int:pk>/', cat_delete, name="cat_delete"),
]

sytecats/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls', namespace="menu")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User,null=True, default=None,on_delete=models.CASCADE)
    address = models.CharField(max_length = 30)

    def __str__(self):
        return "Usuario: %s" % (self.user)

menu/models.py
from django.db import models


class Cat(models.Model):
    name = models.CharField(max_length=20)
    age = models.PositiveIntegerField(default=0)
    food = models.CharField(max_length=20)
    image = models.FileField(upload_to='media')
    state_morning = models.BooleanField(blank=True)
    state_afternoon = models.BooleanField(blank=True)
    state_evening = models.BooleanField(blank=True)

    def __str__(self):
        return self.name

authentication/forms.py
from django import forms
from .models import UserProfile

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        labels = {
            'username': 'Nombre usuario',
            'email': 'Correo',
            'password': 'Contraseña',
            'address': 'Dirección',
        }
        
        widgets = {'address':forms.TextInput(attrs={'class':'form-control col-xs-12', 'placeholder':'Address'}),
                    }

        exclude = ('user','birthdate','gender')

menu/forms.py
from django import forms
from menu.models import Cat

class CreateCatForm(forms.ModelForm):
    class Meta:
        model = Cat
        fields = ['name', 'age', 'food', 'image', 'state_morning', 'state_afternoon', 'state_evening']

authentication/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_user
from django.contrib import messages
from .forms import UserProfileForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, logout as auth_logout, login as auth_login


def login(request):
    if request.POST:
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user.is_staff:
            login_user(request, user)
            #messages.success(request, "Ya esta registrado)
            return HttpResponseRedirect(reverse('menu:list_menu'))
        elif user.is_active:
            login_user(request, user)
            return HttpResponseRedirect(reverse('menu:list_orders'))
        else:
            messages.warning(request, "El usuario no existe")
        return HttpResponseRedirect(reverse('log:login_login'))
    return render(request, 'login.html',{})

def logout(request):
    #return render(request, 'logout.html',{})
    auth_logout(request)
    return HttpResponseRedirect(reverse('log:login_login'))

@login_required(login_url='/register/')
def dashboard(request):
    return render(request, 'dashboard.html',{})

def register(request):
    if request.POST:
        form = UserProfileForm(request.POST)

        if form.is_valid() and not User.objects.filter(username=request.POST['username']).exists():
            user = User.objects.create_user(username=request.POST['username'],
                                            email=request.POST['email'],
                                            password=request.POST['password'])
            form = form.save(commit=False)
            form.user = user
            form.save()
            messages.success(request, "Usuario registrado")
            return HttpResponseRedirect(reverse('log:login_login'))
    else:
        form = UserProfileForm()
    return render(request, 'register.html', {'form':form})

menu/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse
from menu.models import Cat
from menu.forms import CreateCatForm


def cat_list(request):
    template_name = 'menu/cat_list.html'
    cats = Cat.objects.all()
    return render(request, template_name, {'cats': cats})


def cat_create(request):
    if request.method == 'POST':
        form = CreateCatForm(request.POST or None, request.FILES or None)
    else:
        form = CreateCatForm()
    return save_cat_form(request, form, 'menu/partial_cat_create.html')

def save_cat_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            data['form_is_valid'] = True
            cats = Cat.objects.all()
            data['html_cat_list'] = render_to_string('menu/partial_cat_list.html', {
                'cats': cats
            })

        else:
            data['form_is_valid'] = False

    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def cat_update(request, pk):
    cat = get_object_or_404(Cat, pk=pk)
    if request.method == 'POST':
        form = CreateCatForm(request.POST, instance=cat)
    else:
        form = CreateCatForm(instance=cat)
    return save_cat_form(request, form, 'menu/partial_cat_update.html')


def cat_delete(request, pk):
    cat = get_object_or_404(Cat, pk=pk)
    data = dict()
    if request.method == 'POST':
        cat.delete()
        data['form_is_valid'] = True
        cats = Cat.objects.all()
        data['html_cat_list'] = render_to_string('menu/partial_cat_list.html', {
            'cats': cats
        })
    else:
        context = {'cat': cat}
        data['html_form'] = render_to_string('menu/partial_cat_delete.html', context, request=request)
    return JsonResponse(data)

authentication/templates/dashboard.html
{% extends 'base.html' %}
{% block Style %}
{% endblock %}
{% block Content %}
Dashboard
{% endblock %}
{% block JavaScript %}
{% endblock %}

authentication/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon.png' %}">
    <title>Elite Admin Template - The Ultimate Multipurpose admin template</title>
    
    <!-- page css -->
    <link href="{% static 'dist/css/pages/login-register-lock.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">
    
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Elite admin</p>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper" class="login-register login-sidebar" style="background-image:url({% static 'assets/images/background/login-register.jpg' %});">
        <div class="login-box card">
            <div class="card-body">
                {% if messages %}
                {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                        <div class="alert alert-success">
                            <a class="close" href="#" data-dismiss="alert"></a>
                            {{ message }}
                        </div>
                    {% endif %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                        <div class="alert alert-danger">
                            <a class="close" href="#" data-dismiss="alert"></a>
                            {{ message }}
                        </div>
                    {% endif %}
                {% endfor %}
                {% endif %}

                <form class="form-horizontal form-material text-center" id="loginform" action="{% url 'log:login_login' %}" method="POST">
                    {% csrf_token %}
                    <a href="javascript:void(0)" class="db"><img src="{% static 'assets/images/logo-icon.png' %}" alt="Home" /><br/><img src="{% static 'assets/images/logo-text.png' %}" alt="Home" /></a>
                    <div class="form-group m-t-40">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" id="id_username" name="username" placeholder="Username">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-12">
                            <input class="form-control" type="password" required="" id="id_password" name="password" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-info btn-lg btn-block text-uppercase btn-rounded" type="submit">Log in</button>
                        </div>
                    </div>
                    <div class="form-group m-b-0">
                        <div class="col-sm-12 text-center">
                            You do not have an account?<a href="{% url 'log:login_register' %}" class="text-primary m-l-5"><b>Sign up</b></a>
                        </div>
                    </div>
                </form>
                <form class="form-horizontal" id="recoverform" action="index.html">
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <h3>Recover Password</h3>
                            <p class="text-muted">Enter your Email and instructions will be sent to you! </p>
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" required="" placeholder="Email">
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-primary btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Reset</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'assets/node_modules/jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/node_modules/popper/popper.min.js' %}"></script>
    <script src="{% static 'assets/node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!--Custom JavaScript -->
    <script type="text/javascript">
        $(function() {
            $(".preloader").fadeOut();
        });
        $(function() {
            $('[data-toggle="tooltip"]').tooltip()
        });
        // ============================================================== 
        // Login and Recover Password 
        // ============================================================== 
        $('#to-recover').on("click", function() {
            $("#loginform").slideUp();
            $("#recoverform").fadeIn();
        });
    </script>
    
</body>

</html>

authentication/templates/logout.html
{% extends 'base.html' %}
{% block Style %}
{% endblock %}
{% block Content %}
LOGOUT
{% endblock %}
{% block JavaScript %}
{% endblock %}

authentication/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'assets/images/favicon.png' %}">
    <title>Elite Admin Template - The Ultimate Multipurpose admin template</title>
    
    <!-- page css -->
    <link href="{% static 'dist/css/pages/login-register-lock.css' %}" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="{% static 'dist/css/style.min.css' %}" rel="stylesheet">

    
    
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body>
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Elite admin</p>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <section id="wrapper" class="login-register login-sidebar" style="background-image:url({% static 'assets/images/background/login-register.jpg' %});">
        <div class="login-box card">
            <div class="card-body">
                <form class="form-horizontal form-material" id="loginform" action="{% url 'log:login_register' %}" method="post">
                    {% csrf_token %}
                    <div class="text-center">
                        <a href="javascript:void(0)" class="db"><img src="{% static 'assets/images/logo-icon.png' %}" alt="Home" /><br/><img src="{% static 'assets/images/logo-text.png' %}" alt="Home" /></a>
                    </div>
                    <h3 class="box-title m-t-40 m-b-0">Register now</h3><small>Create your account and login</small>
                    <div class="form-group m-t-20">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" name="username" required="" placeholder="Username" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" type="text" name="email" required="" placeholder="Email" autocomplete="off">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            <input class="form-control" id="pass1" name="password" type="password" required="" placeholder="Password">
                        </div>
                    </div>
                    <div class="form-group ">
                        <div class="col-xs-12">
                            {{ form.address }}
                        </div>
                    </div>
                    <div class="form-group text-center m-t-20">
                        <div class="col-xs-12">
                            <button class="btn btn-info btn-lg btn-block text-uppercase waves-effect waves-light" type="submit">Register</button>
                        </div>
                    </div>
                    <div class="form-group m-b-0">
                        <div class="col-sm-12 text-center">
                            <p>Do you already have an account? <a href="{% url 'log:login_login' %}" class="text-info m-l-5"><b>Log in</b></a></p>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="{% static 'assets/node_modules/jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- Bootstrap tether Core JavaScript -->
    <script src="{% static 'assets/node_modules/popper/popper.min.js' %}"></script>
    <script src="{% static 'assets/node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <script type="text/javascript">
        $(function() {
            $(".preloader").fadeOut();
        });  
        $(function() {
            $('[data-toggle="tooltip"]').tooltip()
        });
        // ============================================================== 
        // Login and Recover Password 
        // ============================================================== 
        $('#to-recover').on("click", function() {
            $("#loginform").slideUp();
            $("#recoverform").fadeIn();
        });
    </script>
</body>

</html>

menu/templates/menu/cat_list.html
{% extends 'base.html' %}
{% load static %}
{% block Style %}
{% endblock %}

{% block Content %}

<div class="col-lg-12">
    <div class="card">
        <div class="card-body">
            <h3 class="card-title">My Cats</h3>
            {% if request.user.is_staff %}
            <div class="d-flex">
              <div class="ml-auto p-2">
                  <button type="button" class="btn btn-primary js-create-cat" data-url="{% url 'menu:cat_create' %}">
                      <span class="glyphicon glyphicon-plus"></span>
                      New Cat
              </button><br><br/>
              </div>
            </div>
            {% endif %}
            {% if not request.user.is_staff %}
            <div class="d-flex">
              <div class="ml-auto p-2">
                <a class="btn waves-effect waves-light btn-rounded btn-info" href="#" role="button">Elegir Menu</a><br><br/>
              </div>
            </div>
            {% endif %}
            
            <div class="table-responsive">
                <table class="table" id="cat-table">
                    <thead>
                        <tr>
                            <th class="text-center">#</th>
                            <th class="text-center">Name</th>
                            <th class="text-center">Age</th>
                            <th class="text-center">Food</th>
                            <th class="text-center">Morgning</th>
                            <th class="text-center">Afternoon</th>
                            <th class="text-center">Evening</th>
                            <th class="text-center">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% include 'menu/partial_cat_list.html' %}
                    </tbody>      
                </table>
                <div class="modal fade" id="modal-cat">
                        <div class="modal-dialog">
                            <div class="modal-content">
                            </div>
                        </div>
                    </div>    
            </div>
        </div>
    </div>
</div>



{% endblock %}
{% block JavaScript %}
{% endblock %}

menu/templates/menu/partial_cat_create.html
<form method="POST" action="{% url 'menu:cat_create' %}" enctype="multipart/form-data" class="js-cat-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new cat</h4>
  </div>
  <div class="modal-body">
      {% include 'menu/partial_cat_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create book</button>
  </div>
</form>

menu/templates/menu/partial_cat_delete.html
<form method="post" action="{% url 'menu:cat_delete' cat.id %}" class="js-cat-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm cat deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead" onclick="confirmation(event)">Are you sure you want to delete the Cat  <strong>{{ cat.name }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete cat</button>
  </div>
</form>

menu/templates/menu/partial_cat_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

menu/templates/menu/partial_cat_list.html
{% for b in cats|dictsort:"id" reversed %}
    <tr>
        <td class="text-center">{{ b.pk }}</td>
        <td class="text-center">{{ b.name }}</td>
        <td class="text-center">{{ b.age }}</td>
        <td class="text-center">{{ b.food }}</td>
        <td class="text-center">{{ b.state_morning }}</td>
        <td class="text-center">{{ b.state_afternoon }}</td>
        <td class="text-center">{{ b.state_evening }}</td>
        <td class="text-center">
            <button type="button"
                class="btn btn-warning btn-sm js-update-cat"
                data-url="{% url 'menu:cat_update' b.id %}">
                <span class="glyphicon glyphicon-pencil"></span> Edit
            </button>
            <button type="button"
                class="btn btn-danger btn-sm js-delete-cat"
                data-url="{% url 'menu:cat_delete' b.id %}">
                <span class="glyphicon glyphicon-trash"></span> Delete
            </button>
        </td>
    </tr>
{% endfor %}

menu/templates/menu/partial_cat_update.html
<form method="POST" action="{% url 'menu:cat_update' form.instance.pk %}" enctype="multipart/form-data" class="js-cat-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update book</h4>
  </div>
  <div class="modal-body">
    {% include 'menu/partial_cat_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update cat</button>
  </div>
</form>

templates/_Sidebar.html
{% load static %}
<aside class="left-sidebar">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="user-pro"> <a aria-expanded="false"><img src="{% static 'assets/images/users/5.jpg' %}" alt="user-img" class="img-circle"><span class="hide-menu">{{request.user}}</span></a>

                </li>
                <li class="nav-small-cap">------------</li>
                <li> 
                    <a class="has-arrow waves-effect waves-dark" href="javascript:void(0)" aria-expanded="false">
                        <i class="icon-speedometer"></i>
                        <span class="hide-menu">Dashboard</span>
                    </a>
                    <ul aria-expanded="false" class="collapse">
                        <li><a href="#">Create Publication</a></li>
                        <li><a href="#">Publications</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>